"""empty message

Revision ID: 6a0d26940c2d
Revises: 83376da99571
Create Date: 2024-10-02 16:31:42.813625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a0d26940c2d'
down_revision = '83376da99571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backpack_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_mat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mat_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['study_mat_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flash_card_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('set_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flash_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.String(length=500), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['flash_card_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('backpack_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['backpack_id'], ['backpack_items.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer1', sa.String(length=500), nullable=False),
    sa.Column('answer2', sa.String(length=500), nullable=False),
    sa.Column('answer3', sa.String(length=500), nullable=False),
    sa.Column('answer4', sa.String(length=500), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('correct_answer', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['practice_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    op.drop_table('questions')
    op.drop_table('practice_tests')
    op.drop_table('flash_cards')
    op.drop_table('flash_card_sets')
    op.drop_table('backpack_items')
    # ### end Alembic commands ###
