"""empty message

Revision ID: 7341c25042aa
Revises: 6a0d26940c2d
Create Date: 2024-10-02 21:59:07.989343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7341c25042aa'
down_revision = '6a0d26940c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backpack_items', schema=None) as batch_op:
        batch_op.alter_column('mat_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=25),
               existing_nullable=False)
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=50), nullable=False))

    with op.batch_alter_table('backpack_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['study_mat_id'], ['id'])
        batch_op.alter_column('mat_type',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
