"""empty message

Revision ID: 8a0eb8a05a48
Revises: 5526f0329c00
Create Date: 2024-11-04 15:10:32.195927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0eb8a05a48'
down_revision = '5526f0329c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flashcard_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['flash_cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('test_images')
    op.drop_table('flashcard_images')
    # ### end Alembic commands ###
