"""empty message

Revision ID: 9e897e59fa64
Revises: 8a0eb8a05a48
Create Date: 2025-01-20 13:30:17.034816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e897e59fa64'
down_revision = '8a0eb8a05a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('flash_card_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_name', sa.String(length=50), nullable=False))

    with op.batch_alter_table('practice_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_name', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_tests', schema=None) as batch_op:
        batch_op.drop_column('owner_name')

    with op.batch_alter_table('flash_card_sets', schema=None) as batch_op:
        batch_op.drop_column('owner_name')

    # ### end Alembic commands ###
